<?php
defined('ABSPATH') || exit;
// Bundled, reviewed English copy. Keys are source text, never field IDs: custom copy is not replaced by unrelated defaults.
$map = [
    ', ausgewählte Abreise'=>', selected departure',
    ', ausgewählte Anreise'=>', selected arrival',
    ', ausgewählter Aufenthalt'=>', selected stay',
    'An-/Abreise'=>'Arrival/departure',
    'Anfrage ist zu groß.'=>'The request is too large.',
    'Anfrage wird gesendet …'=>'Sending your request …',
    'Anfragen sind bis drei Jahre im Voraus möglich.'=>'You can request a stay up to three years in advance.',
    'Anreise: {arrival}. Bitte die Abreise auswählen.'=>'Arrival: {arrival}. Please select your departure date.',
    'Aufschlag für zusätzliche Gäste'=>'Additional guest surcharge',
    'Ausgewählt'=>'Selected',
    'Ausgewählt: {arrival} bis {departure} (Abreisetag).'=>'Selected: {arrival} to {departure} (departure date).',
    'Belegt'=>'Booked',
    'Bestätigung nicht möglich: Der Zeitraum ist bereits belegt.'=>'The booking cannot be confirmed: these dates are already booked.',
    'Betrag'=>'Amount',
    'Betrag bitte als Zahl mit maximal zwei Nachkommastellen eingeben.'=>'Please enter an amount with no more than two decimal places.',
    'Bitte ausfüllen: {field}'=>'Please complete: {field}',
    'Bitte die Datenschutzhinweise und Buchungsbedingungen bestätigen.'=>'Please acknowledge the privacy notice and booking terms.',
    'Bitte eine gültige E-Mail-Adresse eingeben.'=>'Please enter a valid email address.',
    'Bitte einen zukünftigen Aufenthalt mit Abreise nach der Anreise wählen.'=>'Please select a future stay with departure after arrival.',
    'Bitte wählen'=>'Please choose',
    'Buchung nicht gefunden.'=>'Booking not found.',
    'Buchungssystem ist beschäftigt. Bitte erneut versuchen.'=>'The booking system is busy. Please try again.',
    'Datenschutzhinweise'=>'privacy notice',
    'Der Gastgeber hat die Preise noch nicht freigeschaltet.'=>'The host has not yet published the prices.',
    'Der Gastgeber muss noch die Datenschutzhinweise einrichten.'=>'The host still needs to set up the privacy notice.',
    'Der Spam-Schutz benötigt HTTPS und einen aktuellen Browser. Bitte die sichere Website verwenden.'=>'Spam protection requires HTTPS and an up-to-date browser. Please use the secure website.',
    'Der gewünschte Zeitraum ist belegt.'=>'Your requested dates are already booked.',
    'Die Anfrage konnte nicht gespeichert werden.'=>'Your request could not be saved.',
    'Die Anfrage konnte nicht verarbeitet werden. Bitte später erneut versuchen.'=>'Your request could not be processed. Please try again later.',
    'Diese Anfrage wurde bereits verarbeitet. Bitte neu laden.'=>'This request has already been processed. Please reload the page.',
    'Dieser Statuswechsel ist nicht zulässig.'=>'This status change is not allowed.',
    'Dieser Zeitraum ist inzwischen belegt. Bitte andere Daten wählen.'=>'These dates have just been booked. Please choose different dates.',
    'Eine entsperrte Sperrzeit kann nicht als Gästebuchung bestätigt werden.'=>'An unblocked period cannot be confirmed as a guest booking.',
    'Endreinigung'=>'Final cleaning',
    'Endreinigung einmalig: '=>'One-off final cleaning fee: ',
    'Enthaltene Umsatzsteuer ({rate} %): {amount}'=>'VAT included ({rate}%): {amount}',
    'Feldinhalt zu lang oder ungültig.'=>'The field value is too long or invalid.',
    'Frei'=>'Available',
    'Für Kalender, Preisberechnung und Spam-Schutz ist JavaScript erforderlich.'=>'JavaScript is required for the calendar, price calculation and spam protection.',
    'Halbe Markierung: Vormittag bzw. Nachmittag belegt. Ein Gästewechsel am selben Tag ist möglich.'=>'Half-day shading means the morning or afternoon is booked. Guests can depart and arrive on the same day.',
    'Leistung'=>'Description',
    'Mindestaufenthalt: {nights} Nächte; maximal 90 Nächte.'=>'Minimum stay: {nights} nights; maximum 90 nights.',
    'Nachmittag belegt, Abreise möglich'=>'Afternoon booked; departure possible',
    'Name oder E-Mail-Adresse ist zu lang.'=>'The name or email address is too long.',
    'Nächster Monat'=>'Next month',
    'Preis wird berechnet …'=>'Calculating the price …',
    'Rate limiter unavailable'=>'Request limit service unavailable',
    'Spam-Schutz abgelaufen oder ungültig. Bitte erneut absenden.'=>'Spam protection has expired or is invalid. Please submit again.',
    'Spam-Schutz ungültig. Bitte erneut absenden.'=>'Spam protection is invalid. Please submit again.',
    'Spam-Schutz wird berechnet …'=>'Checking spam protection …',
    'Status konnte nicht gespeichert werden.'=>'The status could not be saved.',
    'Ungültige Anfrage.'=>'Invalid request.',
    'Ungültige Anzahl.'=>'Invalid number.',
    'Ungültige Auswahl.'=>'Invalid selection.',
    'Ungültiger Spam-Schutz.'=>'Invalid spam protection.',
    'Ungültiges Datum.'=>'Invalid date.',
    'Ungültiges Kontrollkästchen.'=>'Invalid checkbox value.',
    'Unterkunft ({nights} Nächte)'=>'Accommodation ({nights} nights)',
    'Verbindung fehlgeschlagen.'=>'Connection failed.',
    'Verfügbarkeit konnte nicht geprüft werden.'=>'Availability could not be checked.',
    'Verfügbarkeit wird geladen …'=>'Loading availability …',
    'Vielen Dank! Deine Anfrage wurde gespeichert. Die Buchung gilt erst nach Bestätigung durch den Gastgeber.'=>'Thank you! Your request has been saved. Your booking is only valid once the host confirms it.',
    'Vorheriger Monat'=>'Previous month',
    'Vormittag belegt, Anreise möglich'=>'Morning booked; arrival possible',
    'Wähle Anreise und Abreise.'=>'Select your arrival and departure dates.',
    'Wähle zuerst die Anreise, danach die Abreise.'=>'Select your arrival date first, then your departure date.',
    'Zu viele Versuche. Bitte eine Minute warten.'=>'Too many attempts. Please wait one minute.',
    'Zu viele Zeichen: {field}'=>'Too many characters: {field}',
    'belegt'=>'booked', 'frei'=>'available',
    'je Aufenthalt'=>'per stay', 'je zusätzlicher Person'=>'per additional guest',
    'noch nicht festgelegt'=>'not yet set', 'pro Buchung'=>'per booking', 'und Nacht'=>'per night',
    'vergangen'=>'past',
    'Vorschau – es wird keine Anfrage versendet.'=>'Preview – no request will be sent.',
    'Spam-Schutz hat zu lange gedauert. Bitte erneut versuchen.'=>'Spam protection took too long. Please try again.',
    'Spam-Schutz konnte nicht gestartet werden.'=>'Spam protection could not be started.',
    ' Deine Referenz: '=>' Your reference: ',
    'Deine Anfrage wurde gespeichert.'=>'Your request has been saved.',
    'ZEIT FÜR EINE AUSZEIT'=>'TIME FOR A BREAK',
    'Dein Aufenthalt in {property_name}'=>'Your stay at {property_name}',
    'Wähle deinen Wunschzeitraum und frage unverbindlich an.'=>'Choose your preferred dates and send a no-obligation enquiry.',
    'Deine Buchungsanfrage'=>'Your booking enquiry',
    'Ihre Buchungsanfrage'=>'Your booking enquiry',
    'Belegungskalender'=>'Availability calendar',
    'Gut zu wissen'=>'Good to know',
    'Anreise'=>'Arrival', 'Abreise'=>'Departure', 'Gäste gesamt'=>'Total guests',
    'Davon ortstaxenpflichtig'=>'Guests liable for tourist tax',
    'Preisberechnung'=>'Price calculation',
    'Wähle deine Reisedaten, um den Preis zu berechnen.'=>'Select your travel dates to calculate the price.',
    'Vor- und Nachname'=>'Full name', 'E-Mail-Adresse'=>'Email address',
    'Rechnungsadresse (Straße, PLZ, Ort, Land)'=>'Billing address (street, postcode, city, country)',
    'Telefon'=>'Phone', 'Deine Nachricht'=>'Your message', 'Ihre Nachricht'=>'Your message',
    'Ich habe die Buchungsbedingungen und die {privacy_link} gelesen.'=>'I have read the booking terms and the {privacy_link}.',
    'Unverbindlich anfragen'=>'Send enquiry',
    '{total} für {nights} Nächte'=>'{total} for {nights} nights',
    'Anzahlung {deposit} · Restbetrag {balance}. Ortstaxe separat vor Ort: {local_tax}.'=>'Deposit {deposit} · Balance {balance}. Tourist tax payable separately on site: {local_tax}.',
    'Preis pro Nacht für die gesamte Wohnung: {night_price}, für bis zu {included_guests} Gäste.'=>'Price per night for the entire apartment: {night_price}, for up to {included_guests} guests.',
    'Aufschlag bei mehr Gästen: {extra_price} {extra_basis}.'=>'Additional guest surcharge: {extra_price} {extra_basis}.',
    'Mindestaufenthalt: {min_nights} Nächte. Anreise ab {checkin}, Abreise bis {checkout}.'=>'Minimum stay: {min_nights} nights. Check-in from {checkin}, check-out by {checkout}.',
    'Anzahlung: {deposit_percent} %. Restzahlung spätestens {balance_days} Tag(e) vor Anreise per Überweisung.'=>'Deposit: {deposit_percent}%. The balance must be paid by bank transfer no later than {balance_days} day(s) before arrival.',
    'Kostenfreie Stornierung bis {cancel_days} Tage vor Anreise. Spätere Stornierung nach Rücksprache.'=>'Free cancellation up to {cancel_days} days before arrival. Please contact us regarding later cancellations.',
    'Ortstaxe: {local_tax}. {tax_note}'=>'Tourist tax: {local_tax}. {tax_note}',
    'Ferienwohnung'=>'Holiday apartment',
    'Ferienwohnung Maya'=>'Ferienwohnung Maya',
    'Dein Aufenthalt in Ferienwohnung Maya'=>'Your stay at Ferienwohnung Maya',
    'Ihr Aufenthalt in Ferienwohnung Maya'=>'Your stay at Ferienwohnung Maya',
    'Wunschzeitraum auswählen und unverbindlich anfragen.'=>'Choose your preferred dates and send a no-obligation enquiry.',
    'Überschrift'=>'Heading', 'Freier Text'=>'Free text', 'Dein Text'=>'Your text',
    'Textfeld'=>'Text field', 'E-Mail-Feld'=>'Email', 'Telefonfeld'=>'Phone',
    'Nachrichtenfeld'=>'Message', 'Auswahlfeld'=>'Selection', 'Kontrollkästchen'=>'Checkbox',
    'Zustimmung / Datenschutz'=>'Consent / privacy', 'Absenden'=>'Submit',
    'Ja'=>'Yes', 'Nein'=>'No',
    'Rauchen ist nicht gestattet. Haustiere sind aus Rücksicht auf Allergiker nicht erlaubt.'=>'Smoking is not permitted. Pets are not allowed out of consideration for guests with allergies.',
    'Ortstaxe pro Person und Nacht, vor Ort bar zu bezahlen. Befreit: Kinder und Jugendliche bis einschließlich 18 Jahren sowie Personen mit Behinderung ab 50 %. Bitte nur die Anzahl der abgabepflichtigen Gäste angeben; keine Gesundheitsnachweise hochladen.'=>'Tourist tax is charged per person per night and is payable in cash on site. Exempt: children and young people aged 18 or under, and people with a recognised disability of 50% or more. Please enter only the number of guests liable for the tax; do not upload medical documents.',
    'Herzliche Grüße'=>'Warm regards', 'Viele Grüße'=>'Kind regards', 'Liebe Grüße'=>'Best wishes',
    'Mit freundlichen Grüßen'=>'Kind regards', 'Dein Team von {property_name}'=>'Your team at {property_name}',
];
$templates = [
    'request_subject'=>'Your enquiry {booking_number} – {property_name}',
    'request_body'=>"Hello {name},\n\nThank you for your enquiry for {arrival} to {departure} ({nights} nights, {guests} guests).\nTotal accommodation price: {total}. Tourist tax payable separately on site: {local_tax}.\nThis is not yet a booking confirmation. We will get back to you.\n\n{property_name}",
    'confirmed_subject'=>'Booking confirmation {booking_number} – {property_name}',
    'confirmed_body'=>"Hello {name},\n\nYour booking from {arrival} to {departure} is confirmed.\nCheck-in from {checkin}, check-out by {checkout}.\nTotal price: {total}\nPlease pay the deposit of {deposit} by bank transfer to confirm your booking.\nThe remaining balance of {balance} is due by {due_date}; for a last-minute booking, please pay immediately.\nBank details: {iban}\nPayment reference: {booking_number}\nFree cancellation up to and including {cancel_date}. Please contact us for cancellations after this date.\nTourist tax payable separately in cash on site: {local_tax}.\n{tax_note}\n{rules}\n\n{property_name}",
    'cancelled_subject'=>'Cancellation {booking_number}',
    'cancelled_body'=>"Hello {name},\n\nYour booking from {arrival} to {departure} has been cancelled.\nWe will discuss any refunds or cancellation fees with you separately.\n\n{property_name}",
    'rejected_subject'=>'Your enquiry {booking_number}',
    'rejected_body'=>"Hello {name},\n\nUnfortunately, we are unable to confirm your request for {arrival} to {departure}.\n\n{property_name}",
    'invoice_subject'=>'Your invoice {invoice_number}',
    'invoice_body'=>"Hello {name},\n\nPlease find attached your invoice {invoice_number} for your stay from {arrival} to {departure}.\n\n{property_name}",
    'pdf_header'=>'<strong>{property_name}</strong><br>{seller}',
    'pdf_body'=>'<h1>Invoice {invoice_number}</h1><p>Invoice date: {invoice_date}<br>Booking: {booking_number}</p><p>{name}<br>{address}</p><h2>Your stay</h2><p>{arrival} to {departure} · {nights} nights · {guests} guests</p>{items}<p><strong>Invoice total: {total}</strong><br>{vat_note}</p><p>Deposit: {deposit}<br>Balance: {balance}, due on {due_date}<br>Bank details: {iban}</p><p>Tourist tax: {local_tax} – payable separately in cash on site, not included in the invoice total.</p><p>{invoice_note}</p>',
    'pdf_footer'=>'{property_name} · {tax_id}<br>{iban}',
];
foreach (FWB_Settings::template_defaults() as $key=>$source) {
    $target=$templates[$key];$map[$source]=$target;
    // Standard mail bodies may already have been saved by the visual editor.
    if(str_ends_with($key,'_body')&&!str_starts_with($key,'pdf_'))$map[wpautop(esc_html($source))]=wpautop(esc_html($target));
    $de=preg_split('/<[^>]*>|\r?\n/u',$source);$en=preg_split('/<[^>]*>|\r?\n/u',$target);
    if(count($de)===count($en))foreach($de as $i=>$part)if(trim($part)!=='')$map[$part]=$en[$i];
}
return $map;
