<?php
defined('ABSPATH') || exit;
return [", ausgewählte Abreise",
", ausgewählte Anreise",
", ausgewählter Aufenthalt",
"An-/Abreise",
"Anfrage ist zu groß.",
"Anfrage wird gesendet …",
"Anfragen sind bis drei Jahre im Voraus möglich.",
"Anreise: {arrival}. Bitte die Abreise auswählen.",
"Aufschlag für zusätzliche Gäste",
"Ausgewählt",
"Ausgewählt: {arrival} bis {departure} (Abreisetag).",
"Belegt",
"Bestätigung nicht möglich: Der Zeitraum ist bereits belegt.",
"Betrag",
"Betrag bitte als Zahl mit maximal zwei Nachkommastellen eingeben.",
"Bitte ausfüllen: {field}",
"Bitte die Datenschutzhinweise und Buchungsbedingungen bestätigen.",
"Bitte eine gültige E-Mail-Adresse eingeben.",
"Bitte einen zukünftigen Aufenthalt mit Abreise nach der Anreise wählen.",
"Bitte wählen",
"Buchung nicht gefunden.",
"Buchungssystem ist beschäftigt. Bitte erneut versuchen.",
"Datenschutzhinweise",
"Der Gastgeber hat die Preise noch nicht freigeschaltet.",
"Der Gastgeber muss noch die Datenschutzhinweise einrichten.",
"Der Spam-Schutz benötigt HTTPS und einen aktuellen Browser. Bitte die sichere Website verwenden.",
"Der gewünschte Zeitraum ist belegt.",
"Die Anfrage konnte nicht gespeichert werden.",
"Die Anfrage konnte nicht verarbeitet werden. Bitte später erneut versuchen.",
"Diese Anfrage wurde bereits verarbeitet. Bitte neu laden.",
"Dieser Statuswechsel ist nicht zulässig.",
"Dieser Zeitraum ist inzwischen belegt. Bitte andere Daten wählen.",
"Eine entsperrte Sperrzeit kann nicht als Gästebuchung bestätigt werden.",
"Endreinigung",
"Endreinigung einmalig: ",
"Enthaltene Umsatzsteuer ({rate} %): {amount}",
"Feldinhalt zu lang oder ungültig.",
"Frei",
"Für Kalender, Preisberechnung und Spam-Schutz ist JavaScript erforderlich.",
"Halbe Markierung: Vormittag bzw. Nachmittag belegt. Ein Gästewechsel am selben Tag ist möglich.",
"Leistung",
"Mindestaufenthalt: {nights} Nächte; maximal 90 Nächte.",
"Nachmittag belegt, Abreise möglich",
"Name oder E-Mail-Adresse ist zu lang.",
"Nächster Monat",
"Preis wird berechnet …",
"Rate limiter unavailable",
"Spam-Schutz abgelaufen oder ungültig. Bitte erneut absenden.",
"Spam-Schutz ungültig. Bitte erneut absenden.",
"Spam-Schutz wird berechnet …",
"Status konnte nicht gespeichert werden.",
"Ungültige Anfrage.",
"Ungültige Anzahl.",
"Ungültige Auswahl.",
"Ungültiger Spam-Schutz.",
"Ungültiges Datum.",
"Ungültiges Kontrollkästchen.",
"Unterkunft ({nights} Nächte)",
"Verbindung fehlgeschlagen.",
"Verfügbarkeit konnte nicht geprüft werden.",
"Verfügbarkeit wird geladen …",
"Vielen Dank! Deine Anfrage wurde gespeichert. Die Buchung gilt erst nach Bestätigung durch den Gastgeber.",
"Vorheriger Monat",
"Vormittag belegt, Anreise möglich",
"Wähle Anreise und Abreise.",
"Wähle zuerst die Anreise, danach die Abreise.",
"Zu viele Versuche. Bitte eine Minute warten.",
"Zu viele Zeichen: {field}",
"belegt",
"frei",
"je Aufenthalt",
"je zusätzlicher Person",
"noch nicht festgelegt",
"pro Buchung",
"und Nacht",
"vergangen","Vorschau – es wird keine Anfrage versendet.",
"Spam-Schutz hat zu lange gedauert. Bitte erneut versuchen.",
"Spam-Schutz konnte nicht gestartet werden.",
" Deine Referenz: ",
"Deine Anfrage wurde gespeichert."];
